namespace DesignDocService.Dtos
{
    /// <summary>
    /// Request payload used to create a new design document. Content represents the markdown
    /// body of the document and is stored in the Git repository, not in the database.
    /// </summary>
    public class CreateDocumentRequest
    {
        public string Title { get; set; } = string.Empty;
        public string Product { get; set; } = string.Empty;
        public string Team { get; set; } = string.Empty;
        public string Author { get; set; } = string.Empty;
        public string TaskLink { get; set; } = string.Empty;
        public string Content { get; set; } = string.Empty;
        public string GitRepository { get; set; } = string.Empty;
        public string GitFilePath { get; set; } = string.Empty;
        /// <summary>
        /// Optional commit hash to associate with the initial version. If omitted, a new commit
        /// identifier will be generated by the Git service.
        /// </summary>
        public string? GitCommitHash { get; set; }
        /// <summary>
        /// Optional initial status of the document. Defaults to Draft.
        /// </summary>
        public Models.DocumentStatus Status { get; set; } = Models.DocumentStatus.Draft;
    }
}